### ISSUE TITLE
relocation.s has two arguments to load?

### ISSUE THREAD

**Issue by kripken** [WebAssembly/experimental#54]
````
i32.load $0, $pop0
````

What's going on here? :)

**Comment by sunfishcode** [comment]
Unlike most of the other tests, relocation.s is a hand-written testcase. This looks like a case of "human error" :).

**Comment by kripken** [comment]
Heh, ok :)

**Comment by sunfishcode** [comment]
Fixed in d6e7df2f00ee4f21859b7877e563ce46ef58bb94.
