### ISSUE TITLE
wasmate: align function pointer bits on .align

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/experimental#81]
@sunfishcode points out in #79 that it could make sense to use `.align` on a function to force the function table's bits to have a certain value. That should be possible when we emit the `(table ...)`, but I'd like to construct a good testcase for this before addressing the issue.

**Comment by sunfishcode** [comment]
Can we just revert the change? This is a known silent miscompile waiting to happen.

**Comment by jfbastien** [comment]
I would rather fix the issue instead: it's not hard and I doubt this is going to cause breakage before it's fixed.

Developers are already in murky waters when they rely on `__attribute__((aligned(#)))`: it's not standard C++, and even the GCC documentation warn the traveler of inherent perils around linkertown:

> `aligned` (alignment)
> This attribute specifies a minimum alignment for the function, measured in bytes.
> You cannot use this attribute to decrease the alignment of a function, only to increase it. However, when you explicitly specify a function alignment this overrides the effect of the -falign-functions (see Optimize Options) option for this function.
> 
> Note that the effectiveness of aligned attributes may be limited by inherent limitations in your linker. On many systems, the linker is only able to arrange for functions to be aligned up to a certain maximum alignment. (For some linkers, the maximum supported alignment may be very very small.) See your linker documentation for further information.

**Comment by jfbastien** [comment]
Obsolete, wasmate is now gone. Closing.
