### ISSUE TITLE
cfg-stackify output looks wrong

### ISSUE THREAD

**Issue by kripken** [WebAssembly/experimental#84]
It has

`(i32.and (call_import $a) (get_local 1))`

where 1 is an i32, but 

`(import $a "misctest" "a" (param i32))`

with no return value.

**Comment by sunfishcode** [comment]
Where does this occur? I'm looking [here](https://github.com/WebAssembly/binaryen/blob/master/test/llvm_autogenerated/cfg-stackify.wast#L5) and am seeing `(import $a "env" "a" (result i32))`, which looks correct. This is also what s2wasm emits when run in cfg-stackify.ll.

**Comment by kripken** [comment]
Hmm, perhaps I was mistaken back then, or something changed. I agree it looks fine now.
